blank_issues_enabled: false
contact_links:
  - name: CV Content Help
    url: https://github.com/sasaorasanin/sasaorasanin.github.io/blob/main/README.md
    about: See content format and version rules.
